USE Fitboa;
DROP TABLE IF EXISTS VerifyLogs;
CREATE TABLE IF NOT EXISTS VerifyLogs
(
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,

    UserId INT DEFAULT NULL,

    Contact VARCHAR(13) NOT NULL,

    IsVerified BOOLEAN NOT NULL DEFAULT FALSE,
    VerifyKey VARCHAR(6) NOT NULL DEFAULT SUBSTRING(CONCAT('', RAND()), 3, 6),
    VerifyCount INT NOT NULL DEFAULT 0,
    VerifyTimeout TIMESTAMP NOT NULL DEFAULT DATE_ADD(CURRENT_TIMESTAMP, INTERVAL + 3 MINUTE),

    IsUsed BOOLEAN NOT NULL DEFAULT FALSE,

    Type VARCHAR(32) NOT NULL,

    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = INNODB
DEFAULT CHARSET=UTF8;
