USE Fitboa;
DROP TABLE IF EXISTS FindUserInfo;
CREATE TABLE IF NOT EXISTS FindUserInfo
(
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,

    Name VARCHAR(64) NOT NULL,
    Contact VARCHAR(13) NOT NULL,

    VerifyKey VARCHAR(6) NULL,
    VerifyCount INT DEFAULT 0,
    VerifyTimeout TIMESTAMP NULL,

    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = INNODB
DEFAULT CHARSET=UTF8;