USE Fitboa;
DROP TABLE IF EXISTS FirstDeliveries;
CREATE TABLE IF NOT EXISTS FirstDeliveries
(
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,

    UserId INT NOT NULL,

    Name VARCHAR(64) NOT NULL,
    Contact VARCHAR(13) NOT NULL,

    #Address VARCHAR(256) NOT NULL,
    RoadAddress VARCHAR(256) NOT NULL,
    JibunAddress VARCHAR(256) NOT NULL,
    ExtraAddress VARCHAR(256) NULL,
    PostCode VARCHAR(5) NOT NULL,
    AddressType VARCHAR(6) NOT NULL,

    IsEnd BOOLEAN DEFAULT FALSE,

    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE CASCADE
) ENGINE = INNODB
DEFAULT CHARSET=UTF8; 

