USE Fitboa;
DROP TABLE IF EXISTS BodyTypeServices;
CREATE TABLE IF NOT EXISTS BodyTypeServices
(
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,

    UserId INT NOT NULL,

    Shoulder DOUBLE NOT NULL,
    Chest DOUBLE NOT NULL,
    Waist DOUBLE NOT NULL,
    Arm DOUBLE NOT NULL,
    Leg DOUBLE NOT NULL,
    Thigh DOUBLE NOT NULL,

    IsEnd BOOLEAN DEFAULT FALSE,

    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE CASCADE
) ENGINE = INNODB
DEFAULT CHARSET=UTF8; 

INSERT INTO BodyTypeServices (
    UserId, Shoulder, Chest, Waist, Arm, Leg, Thigh, IsEnd,CreatedAt, UpdatedAt
)
VALUES (
    2, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, FALSE, '2022-02-03 22:20:27', '2022-02-03 22:22:11'
);
