USE Fitboa;
DROP TABLE IF EXISTS MerchantCancelInfos;
CREATE TABLE IF NOT EXISTS MerchantCancelInfos
(
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,

    UserId INT DEFAULT NULL,

    MerchantId INT DEFAULT NULL, 

    ResultCode VARCHAR(6) DEFAULT NULL,
    ResultMsg VARCHAR(100) DEFAULT NULL,
    CancelDateTime TIMESTAMP NULL,
    DetailResultCode VARCHAR(6) DEFAULT NULL,
    ReceiptInfo VARCHAR(40) DEFAULT NULL,
    CancelType VARCHAR(80) DEFAULT NULL, 
    CancelDetail VARCHAR(1024) DEFAULT NULL,

    IsCancel BOOLEAN DEFAULT FALSE,
    
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY(UserId) REFERENCES Users(Id),
    FOREIGN KEY(MerchantId) REFERENCES Merchants(Id)
) ENGINE = INNODB
DEFAULT CHARSET=UTF8;
