USE Fitboa;
DROP TABLE IF EXISTS Bookmarks;
CREATE TABLE IF NOT EXISTS Bookmarks
(
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,

    ContentId INT NOT NULL,
    UserId INT NOT NULL,

    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY(ContentId) REFERENCES Contents(Id) ON DELETE CASCADE,
    FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE CASCADE
) ENGINE = INNODB
DEFAULT CHARSET=UTF8;

#INSERT INTO Bookmarks (ContentId, UserId)
#VALUES (1, 2);
#
#INSERT INTO Bookmarks (ContentId, UserId)
#VALUES (4, 2);
#
#INSERT INTO Bookmarks (ContentId, UserId)
#VALUES (2, 2);
#
#INSERT INTO Bookmarks (ContentId, UserId)
#VALUES (3, 2);