USE Fitboa;
DROP TABLE IF EXISTS UserContentViews;
CREATE TABLE IF NOT EXISTS UserContentViews
(
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,

    UserId INT NOT NULL,
    ContentId INT NOT NULL,

    ContentType INT NOT NULL,

    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY(ContentId) REFERENCES Contents(Id)
) ENGINE = INNODB
DEFAULT CHARSET=UTF8;