USE Fitboa;
DROP TABLE IF EXISTS UserSecessions;
CREATE TABLE IF NOT EXISTS UserSecessions
(
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,

    SecessionContent VARCHAR(2048),
    LongContent BOOLEAN DEFAULT FALSE,

    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = INNODB
DEFAULT CHARSET=UTF8;
