USE Fitboa;
DROP TABLE IF EXISTS FAQs;
CREATE TABLE IF NOT EXISTS FAQs
(
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,

    Title VARCHAR(256) NOT NULL,
    Content VARCHAR(2048) NOT NULL,

    AdminId INT NOT NULL,

    Type VARCHAR(8) NOT NULL DEFAULT '공지사항',
    TypeNum INT NOT NULL DEFAULT 0, #0: 공지사항, 1: FAQ

    Status BOOLEAN NOT NULL DEFAULT TRUE,

    Views INT NOT NULL DEFAULT 0,

    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY(AdminId) REFERENCES Users(Id) ON DELETE CASCADE
) ENGINE = INNODB
DEFAULT CHARSET=UTF8;